<a href="https://colab.research.google.com/github/viktoruebelhart/pos_facens/blob/main/Atividade_2_Pandas_(1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

## Desafio de Pandas com o Dataset Netflix para Pós-Graduação

Este desafio tem como objetivo aprimorar suas habilidades em manipulação e análise de dados usando a biblioteca Pandas do Python, com foco no dataset de títulos da Netflix. Vocês deverão responder a uma série de perguntas e realizar transformações nos dados. Mãos à obra!

### Recursos e Funções Sugeridas

Para completar este desafio, vocês podem usar diversas funções da biblioteca Pandas. Abaixo estão algumas que podem ser úteis para o dataset da Netflix:

**Carregamento e Inspeção de Dados:**
*   `pd.read_csv()`: Para carregar dados.
*   `df.head()`, `df.info()`: Para visão inicial.
*   `df['type'].value_counts()`: Útil para ver a distribuição entre Filmes e Séries.

**Manipulação de Strings e Datas:**
*   `df['date_added'].str.strip()`: Para limpar espaços em branco.
*   `pd.to_datetime()`: Para converter colunas de data.
*   `df['duration'].str.extract()`: Para extrair números de durações (minutos ou temporadas).

**Filtragem e Agregação:**
*   `df[df['release_year'] > 2020]`: Para filtrar lançamentos recentes.
*   `df.groupby('country').size()`: Para contar produções por país.

### Tarefa 1: Carregamento e Visão Geral da Netflix

1.  **Carregue** o dataset da Netflix.
    URL: `https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-04-20/netflix_titles.csv`
2.  **Exiba** as primeiras 5 linhas.
3.  **Verifique** a quantidade de Filmes vs. Séries.
4.  **Identifique** colunas com valores nulos.

In [3]:
#1
data = pd.read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-04-20/netflix_titles.csv')
data

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,TV Show,3%,NaN,"João Miguel, Bianca Comparato, Michel Gomes, R...",Brazil,"August 14, 2020",2020,TV-MA,4 Seasons,"International TV Shows, TV Dramas, TV Sci-Fi &...",In a future where the elite inhabit an island ...
1,s2,Movie,7:19,Jorge Michel Grau,"Demián Bichir, Héctor Bonilla, Oscar Serrano, ...",Mexico,"December 23, 2016",2016,TV-MA,93 min,"Dramas, International Movies",After a devastating earthquake hits Mexico Cit...
2,s3,Movie,23:59,Gilbert Chan,"Tedd Chan, Stella Chung, Henley Hii, Lawrence ...",Singapore,"December 20, 2018",2011,R,78 min,"Horror Movies, International Movies","When an army recruit is found dead, his fellow..."
3,s4,Movie,9,Shane Acker,"Elijah Wood, John C. Reilly, Jennifer Connelly...",United States,"November 16, 2017",2009,PG-13,80 min,"Action & Adventure, Independent Movies, Sci-Fi...","In a postapocalyptic world, rag-doll robots hi..."
4,s5,Movie,21,Robert Luketic,"Jim Sturgess, Kevin Spacey, Kate Bosworth, Aar...",United States,"January 1, 2020",2008,PG-13,123 min,Dramas,A brilliant group of students become card-coun...
...,...,...,...,...,...,...,...,...,...,...,...,...
7782,s7783,Movie,Zozo,Josef Fares,"Imad Creidi, Antoinette Turk, Elias Gergi, Car...","Sweden, Czech Republic, United Kingdom, Denmar...","October 19, 2020",2005,TV-MA,99 min,"Dramas, International Movies",When Lebanon's Civil War deprives Zozo of his ...
7783,s7784,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...
7784,s7785,Movie,Zulu Man in Japan,NaN,Nasty C,NaN,"September 25, 2020",2019,TV-MA,44 min,"Documentaries, International Movies, Music & M...","In this documentary, South African rapper Nast..."
7785,s7786,TV Show,Zumbo's Just Desserts,NaN,"Adriano Zumbo, Rachel Khoo",Australia,"October 31, 2020",2019,TV-PG,1 Season,"International TV Shows, Reality TV",Dessert wizard Adriano Zumbo looks for the nex...
7786,s7787,Movie,ZZ TOP: THAT LITTLE OL' BAND FROM TEXAS,Sam Dunn,NaN,"United Kingdom, Canada, United States","March 1, 2020",2019,TV-MA,90 min,"Documentaries, Music & Musicals",This documentary delves into the mystique behi...

In [4]:
#2 Exiba as primeiras 5 linhas.
data.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,TV Show,3%,NaN,"João Miguel, Bianca Comparato, Michel Gomes, R...",Brazil,"August 14, 2020",2020,TV-MA,4 Seasons,"International TV Shows, TV Dramas, TV Sci-Fi &...",In a future where the elite inhabit an island ...
1,s2,Movie,7:19,Jorge Michel Grau,"Demián Bichir, Héctor Bonilla, Oscar Serrano, ...",Mexico,"December 23, 2016",2016,TV-MA,93 min,"Dramas, International Movies",After a devastating earthquake hits Mexico Cit...
2,s3,Movie,23:59,Gilbert Chan,"Tedd Chan, Stella Chung, Henley Hii, Lawrence ...",Singapore,"December 20, 2018",2011,R,78 min,"Horror Movies, International Movies","When an army recruit is found dead, his fellow..."
3,s4,Movie,9,Shane Acker,"Elijah Wood, John C. Reilly, Jennifer Connelly...",United States,"November 16, 2017",2009,PG-13,80 min,"Action & Adventure, Independent Movies, Sci-Fi...","In a postapocalyptic world, rag-doll robots hi..."
4,s5,Movie,21,Robert Luketic,"Jim Sturgess, Kevin Spacey, Kate Bosworth, Aar...",United States,"January 1, 2020",2008,PG-13,123 min,Dramas,A brilliant group of students become card-coun...

In [5]:
#3 Verifique a quantidade de Filmes vs. Séries.
data['type'].value_counts()

type
Movie      5377
TV Show    2410
Name: count, dtype: int64

In [6]:
#4 Identifique colunas com valores nulos.
data.isnull().sum()

show_id            0
type               0
title              0
director        2389
cast             718
country          507
date_added        10
release_year       0
rating             7
duration           0
listed_in          0
description        0
dtype: int64

### Tarefa 2: Limpeza e Pré-processamento de Dados (Netflix)

1.  **Limpeza de Datas**: Converta a coluna `date_added` para o formato datetime do Pandas. (Dica: use `str.strip()` antes de converter).
2.  **Tratamento de Nulos**: Preencha os valores ausentes na coluna `country` com 'Unknown' e na coluna `director` com 'Not Available'.
3.  **Extração Numérica**: Crie uma nova coluna `duration_num` que contenha apenas o valor numérico da coluna `duration` (ex: '90 min' vira 90, '2 Seasons' vira 2).
4.  **Categorização**: Crie uma coluna `is_movie` que seja 1 se o tipo for 'Movie' e 0 caso contrário.

### Tarefa 3: Análise Exploratória de Dados (EDA) - Expandida

1.  **Top 10 Países**: Quais são os 10 países que mais produzem conteúdo?
2.  **Sazonalidade**: Qual o mês com maior volume de novos títulos adicionados ao catálogo?
3.  **Diretores**: Quem são os 5 diretores com mais títulos na plataforma?
4.  **Distribuição de Rating**: Qual a classificação indicativa predominante?

### Tarefa 4: Manipulações Avançadas e Insights

1.  **Análise de Séries**: Qual a média de temporadas das séries e qual o máximo encontrado?
2.  **Evolução da Duração**: Como a duração média dos filmes (`Movie`) variou nos últimos 10 anos?
3.  **Filtro por Gênero**: Identifique títulos que são simultaneamente 'Documentaries' e produzidos no 'United Kingdom'.
4.  **Segmentação por Era**: Comparação da proporção de Filmes vs Séries em títulos 'Classic' (pré-2010) e 'Modern' (2010+).

### Tarefa 5: Conclusão

Escreva um resumo sobre o que você descobriu no catálogo da Netflix. Qual tipo de conteúdo predomina? Quais países são os maiores hubs de produção e como a biblioteca evoluiu nos últimos anos?