<a href="https://colab.research.google.com/github/viktoruebelhart/pos_facens/blob/main/Desafio_Pr%C3%A1tico_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Desafio de Pandas com o Dataset Titanic para Pós-Graduação

Este desafio tem como objetivo aprimorar suas habilidades em manipulação e análise de dados usando a biblioteca Pandas do Python, com foco no famoso dataset do Titanic. Vocês deverão responder a uma série de perguntas e realizar transformações nos dados. Mãos à obra!

### Recursos e Funções Sugeridas

Para completar este desafio, vocês podem usar diversas funções da biblioteca Pandas. Abaixo estão algumas que podem ser úteis, organizadas por categoria:

**Carregamento e Inspeção de Dados:**
*   `pd.read_csv()`: Para carregar dados de um arquivo CSV.
*   `df.head()`, `df.tail()`: Para visualizar as primeiras/últimas linhas do DataFrame.
*   `df.shape`: Para obter as dimensões do DataFrame (linhas, colunas).
*   `df.info()`: Para um resumo conciso do DataFrame, incluindo tipos de dados e valores não nulos.
*   `df.describe()`: Para estatísticas descritivas das colunas numéricas.
*   `df.columns`: Para listar os nomes das colunas.

**Manipulação de Valores Ausentes:**
*   `df.isnull()`: Para identificar valores ausentes (NaN).
*   `df.isnull().sum()`: Para contar valores ausentes por coluna.
*   `df.fillna()`: Para preencher valores ausentes.
*   `df.dropna()`: Para remover linhas/colunas com valores ausentes.

**Transformação de Dados:**
*   `df['col'].astype()`: Para converter o tipo de dado de uma coluna.
*   `df['col'].replace()`: Para substituir valores específicos em uma coluna.
*   `df['col'].str.extract()`: Para extrair padrões de strings usando expressões regulares.
*   `pd.cut()`: Para categorizar e agrupar dados em faixas (bins).

**Seleção e Filtragem:**
*   `df[]`: Para seleção de colunas ou filtragem de linhas.
*   `df.loc[]`, `df.iloc[]`: Para seleção baseada em rótulo ou posição, respectivamente.

**Agregação e Agrupamento:**
*   `df.groupby()`: Para agrupar dados por uma ou mais colunas.
*   `df.agg()`: Para aplicar múltiplas funções de agregação.
*   `df.pivot_table()`: Para criar tabelas dinâmicas para sumarização de dados.

**Operações Matemáticas e Lógicas:**
*   Operadores aritméticos (`+`, `-`, `*`, `/`) e lógicos (`==`, `!=`, `>`, `<`, `>=`, `<=`, `&`, `|`).

**Documentação Oficial do Pandas:**
*   Para uma referência completa e exemplos detalhados, consultem a documentação oficial do Pandas: [https://pandas.pydata.org/docs/](https://pandas.pydata.org/docs/)

### Tarefa 1: Carregamento e Visão Geral dos Dados

1.  **Carregue** o dataset do Titanic diretamente da URL fornecida em um DataFrame Pandas.
    URL: `https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv`
2.  **Exiba** as primeiras 5 linhas do DataFrame.
3.  **Verifique** o formato (shape) do DataFrame.
4.  **Obtenha** um resumo das informações (info) do DataFrame, incluindo tipos de dados e contagem de valores não nulos.
5.  **Descreva** as estatísticas descritivas (describe) para as colunas numéricas.

In [18]:
import pandas as pd

# 1. Carregar o dataset
titanic_df = pd.read_csv('https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv')

# 2. Exibir as primeiras 5 linhas
print("Primeiras 5 linhas do DataFrame:")
display(titanic_df.head())

# 3. Verificar o formato (shape)
print(f"\nFormato do DataFrame: {titanic_df.shape}")

# 4. Obter um resumo das informações
print("\nInformações do DataFrame:")
titanic_df.info()

# 5. Descrever as estatísticas descritivas
print("\nEstatísticas Descritivas:")
display(titanic_df.describe())

Primeiras 5 linhas do DataFrame:

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

Formato do DataFrame: (891, 12)

Informações do DataFrame:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

Estatísticas Descritivas:

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [9]:
from google.colab import drive
drive.mount('/content/drive')

MessageError: Error: credential propagation was unsuccessful

### Tarefa 2: Limpeza e Pré-processamento de Dados

1.  **Identifique** colunas com valores ausentes. Para cada coluna, mostre a contagem e a porcentagem de valores ausentes.
2.  **Preencha** os valores ausentes na coluna 'Age' com a mediana da idade.
3.  **Preencha** os valores ausentes na coluna 'Embarked' com o modo (valor mais frequente).
4.  **Descarte** a coluna 'Cabin' devido ao alto número de valores ausentes ou à sua complexidade para imputação simples neste desafio.
5.  **Converta** a coluna 'Sex' para valores numéricos (0 para 'male', 1 para 'female').
6.  **Crie** uma nova coluna 'FamilySize' que seja a soma de 'SibSp' (número de irmãos/cônjuges a bordo) e 'Parch' (número de pais/filhos a bordo), mais 1 (para o próprio passageiro).
7.  **Crie** uma nova coluna 'IsAlone' baseada em 'FamilySize' (1 se FamilySize for 1, 0 caso contrário).
8.  **Exiba** novamente `titanic_df.info()` e `titanic_df.head()` para verificar as alterações.

In [19]:
#1 - Identifique colunas com valores ausentes. Para cada coluna, mostre a contagem e a porcentagem de valores ausentes.
titanic_df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [20]:
#2 Preencha os valores ausentes na coluna 'Age' com a mediana da idade.
titanic_df['Age'] = titanic_df['Age'].fillna(titanic_df['Age'].median())
titanic_df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [21]:
#3 Preencha os valores ausentes na coluna 'Embarked' com o modo (valor mais frequente).
titanic_df['Embarked'] = titanic_df['Embarked'].fillna(titanic_df['Embarked'].mode()[0])
titanic_df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         0
dtype: int64

In [22]:
#4 - Descarte a coluna 'Cabin' devido ao alto número de valores ausentes ou à sua complexidade para imputação simples neste desafio.
titanic_df = titanic_df.drop(columns=['Cabin'])
titanic_df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

In [26]:
#5 Converta a coluna 'Sex' para valores numéricos (0 para 'male', 1 para 'female').
print(titanic_df['Sex'].value_counts())
titanic_df['Sex'] = titanic_df['Sex'].replace({'male': 0, 'female': 1})
titanic_df.head()

Sex
male      577
female    314
Name: count, dtype: int64

/tmp/ipykernel_919/1498920401.py:3: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  titanic_df['Sex'] = titanic_df['Sex'].replace({'male': 0, 'female': 1})

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",0,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",1,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",0,35.0,0,0,373450,8.0500,S

In [27]:
#6 Crie uma nova coluna 'FamilySize' que seja a soma de 'SibSp'
 #(número de irmãos/cônjuges a bordo) e 'Parch' (número de pais/filhos a bordo), mais 1 (para o próprio passageiro).

titanic_df['FamilySize'] = titanic_df['SibSp'] + titanic_df['Parch'] + 1
titanic_df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,FamilySize
0,1,0,3,"Braund, Mr. Owen Harris",0,22.0,1,0,A/5 21171,7.2500,S,2
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,38.0,1,0,PC 17599,71.2833,C,2
2,3,1,3,"Heikkinen, Miss. Laina",1,26.0,0,0,STON/O2. 3101282,7.9250,S,1
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,35.0,1,0,113803,53.1000,S,2
4,5,0,3,"Allen, Mr. William Henry",0,35.0,0,0,373450,8.0500,S,1

In [28]:
#7 Crie uma nova coluna 'IsAlone' baseada em 'FamilySize' (1 se FamilySize for 1, 0 caso contrário).
titanic_df['IsAlone'] = (titanic_df['FamilySize'] == 1).astype(int)
titanic_df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,FamilySize,IsAlone
0,1,0,3,"Braund, Mr. Owen Harris",0,22.0,1,0,A/5 21171,7.2500,S,2,0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,38.0,1,0,PC 17599,71.2833,C,2,0
2,3,1,3,"Heikkinen, Miss. Laina",1,26.0,0,0,STON/O2. 3101282,7.9250,S,1,1
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,35.0,1,0,113803,53.1000,S,2,0
4,5,0,3,"Allen, Mr. William Henry",0,35.0,0,0,373450,8.0500,S,1,1

In [30]:
#8 Exiba novamente titanic_df.info() e titanic_df.head() para verificar as alterações.
titanic_df.info()
titanic_df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    int64
 5   Age          891 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Embarked     891 non-null    object
 11  FamilySize   891 non-null    int64
 12  IsAlone      891 non-null    int64
dtypes: float64(2), int64(8), object(3)
memory usage: 90.6+ KB

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,FamilySize,IsAlone
0,1,0,3,"Braund, Mr. Owen Harris",0,22.0,1,0,A/5 21171,7.2500,S,2,0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,38.0,1,0,PC 17599,71.2833,C,2,0
2,3,1,3,"Heikkinen, Miss. Laina",1,26.0,0,0,STON/O2. 3101282,7.9250,S,1,1
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,35.0,1,0,113803,53.1000,S,2,0
4,5,0,3,"Allen, Mr. William Henry",0,35.0,0,0,373450,8.0500,S,1,1

### Tarefa 3: Análise Exploratória de Dados (EDA) com Pandas

1.  **Qual** a proporção de sobreviventes no total?
2.  **Calcule** a taxa de sobrevivência por gênero.
3.  **Calcule** a taxa de sobrevivência por classe de passageiro ('Pclass').
4.  **Determine** a idade média dos sobreviventes e dos não-sobreviventes.
5.  **Encontre** a porta de embarque (Embarked) mais comum e a taxa de sobrevivência para cada porta.
6.  **Crie** uma tabela dinâmica (pivot table) mostrando a taxa de sobrevivência média por 'Pclass' e 'Sex'.

In [62]:
#1 Qual a proporção de sobreviventes no total?
titanic_df['Survived'].value_counts(normalize=True)*100

Survived
0    61.616162
1    38.383838
Name: proportion, dtype: float64

In [63]:
#2 Calcule a taxa de sobrevivência por gênero.
genero_sobre = titanic_df.groupby('Sex')['Survived'].mean()*100
genero_sobre

Sex
0    18.890815
1    74.203822
Name: Survived, dtype: float64

In [37]:
#3 Calcule a taxa de sobrevivência por classe de passageiro ('Pclass').
classe_sobre = titanic_df.groupby('Pclass')['Survived'].mean()
classe_sobre

Pclass
1    0.629630
2    0.472826
3    0.242363
Name: Survived, dtype: float64

In [38]:
#4 Determine a idade média dos sobreviventes e dos não-sobreviventes.
idade_sobre = titanic_df.groupby('Survived')['Age'].mean()
idade_sobre

Survived
0    30.028233
1    28.291433
Name: Age, dtype: float64

In [47]:
#5 Encontre a porta de embarque (Embarked) mais comum e a taxa de sobrevivência para cada porta.
embarked_moda = titanic_df['Embarked'].mode()[0]
print(f'Porta de embarque mais comum: {embarked_moda}')

embarked_sobre = titanic_df.groupby('Embarked')['Survived'].mean()
embarked_sobre

Porta de embarque mais comum: S

Embarked
C    0.553571
Q    0.389610
S    0.339009
Name: Survived, dtype: float64

In [65]:
#6 Crie uma tabela dinâmica (pivot table) mostrando a taxa de sobrevivência média por 'Pclass' e 'Sex'.
tabela_dinamica = titanic_df.pivot_table(
    values='Survived',
    index='Pclass',
    columns='Sex',
    aggfunc='mean'
)
print("Taxa de Sobrevivência Média por Classe e Gênero:")
tabela_dinamica

Taxa de Sobrevivência Média por Classe e Gênero:

Sex            0         1
Pclass
1       0.368852  0.968085
2       0.157407  0.921053
3       0.135447  0.500000

### Tarefa 4: Manipulações Avançadas com Pandas

1.  **Crie** uma coluna 'AgeGroup' categorizando a idade em faixas: 'Criança' (0-12), 'Adolescente' (13-18), 'Adulto' (19-59), 'Idoso' (60+). Use `pd.cut`.
2.  **Encontre** a taxa de sobrevivência para cada 'AgeGroup'.
3.  **Identifique** os 5 nomes de passageiros mais comuns no dataset (após limpeza, se aplicável, ou apenas a coluna 'Name'). Nota: Isso pode ser complicado devido à variação de nomes. Uma abordagem pode ser extrair apenas o sobrenome ou o título.
4.  **Conte** a frequência de cada título (e.g., Mr., Miss., Mrs., Master.) na coluna 'Name'. Você pode extrair o título usando expressões regulares ou manipulação de strings. Ex: `df['Name'].str.extract(' ([A-Za-z]+)\.')`.
5.  **Calcule** a tarifa ('Fare') média por 'Pclass' e 'Embarked'.

In [53]:
#1 Crie uma coluna 'AgeGroup' categorizando a idade em faixas: 'Criança' (0-12), 'Adolescente' (13-18), 'Adulto' (19-59), 'Idoso' (60+). Use pd.cut.
import pandas as pd
import numpy as np

#(bins)
bins = [0, 12, 18, 59, np.inf]

#categorias
labels = ['Criança', 'Adolescente', 'Adulto', 'Idoso']

titanic_df['AgeGroup'] = pd.cut(titanic_df['Age'], bins=bins, labels=labels)

titanic_df[['Age', 'AgeGroup']].head(20)

     Age     AgeGroup
0   22.0       Adulto
1   38.0       Adulto
2   26.0       Adulto
3   35.0       Adulto
4   35.0       Adulto
5   28.0       Adulto
6   54.0       Adulto
7    2.0      Criança
8   27.0       Adulto
9   14.0  Adolescente
10   4.0      Criança
11  58.0       Adulto
12  20.0       Adulto
13  39.0       Adulto
14  14.0  Adolescente
15  55.0       Adulto
16   2.0      Criança
17  28.0       Adulto
18  31.0       Adulto
19  28.0       Adulto

In [54]:
#2 Encontre a taxa de sobrevivência para cada 'AgeGroup'.
agegroup_sobre = titanic_df.groupby('AgeGroup')['Survived'].mean()
agegroup_sobre

/tmp/ipykernel_919/917510004.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  agegroup_sobre = titanic_df.groupby('AgeGroup')['Survived'].mean()

AgeGroup
Criança        0.579710
Adolescente    0.428571
Adulto         0.365014
Idoso          0.269231
Name: Survived, dtype: float64

In [66]:
#3 Identifique os 5 nomes de passageiros mais comuns no dataset (após limpeza, se aplicável, ou apenas a coluna 'Name').
#Nota: Isso pode ser complicado devido à variação de nomes. Uma abordagem pode ser extrair apenas o sobrenome ou o título.

# Extraindo o sobrenome (tudo que vem antes da vírgula)
titanic_df['Surname'] = titanic_df['Name'].str.split(',').str[0]

#  5 primeiros
top_5_sobrenomes = titanic_df['Surname'].value_counts().head(5)

print("Os 5 sobrenomes mais comuns:")
top_5_sobrenomes

Os 5 sobrenomes mais comuns:

Surname
Andersson    9
Sage         7
Skoog        6
Panula       6
Carter       6
Name: count, dtype: int64

In [60]:
#4 Conte a frequência de cada título (e.g., Mr., Miss., Mrs., Master.) na coluna 'Name'.
#Você pode extrair o título usando expressões regulares ou manipulação de strings. Ex: df['Name'].str.extract(' ([A-Za-z]+)\.').

# Ele procura um espaço, seguido de letras, terminando com um ponto
titanic_df['Title'] = titanic_df['Name'].str.extract(' ([A-Za-z]+)\.', expand=False)

#frequentes
top_5_titulos = titanic_df['Title'].value_counts().head(5)

print("\nOs 5 títulos mais comuns:")
top_5_titulos

Os 5 títulos mais comuns:

<>:5: SyntaxWarning: invalid escape sequence '\.'
<>:5: SyntaxWarning: invalid escape sequence '\.'
/tmp/ipykernel_919/2834483203.py:5: SyntaxWarning: invalid escape sequence '\.'
  titanic_df['Title'] = titanic_df['Name'].str.extract(' ([A-Za-z]+)\.', expand=False)

Title
Mr        517
Miss      182
Mrs       125
Master     40
Dr          7
Name: count, dtype: int64

In [61]:
#5 Calcule a tarifa ('Fare') média por 'Pclass' e 'Embarked'.
tarifa_media = titanic_df.groupby(['Pclass', 'Embarked'])['Fare'].mean()
tarifa_media

Pclass  Embarked
1       C           104.718529
        Q            90.000000
        S            70.514244
2       C            25.358335
        Q            12.350000
        S            20.327439
3       C            11.214083
        Q            11.183393
        S            14.644083
Name: Fare, dtype: float64

### Tarefa 5: Conclusão

Após completar as tarefas acima, escreva um pequeno parágrafo (em uma célula de markdown) resumindo as principais descobertas sobre a sobrevivência no Titanic, baseando-se em sua análise de dados. Quais fatores parecem ter tido o maior impacto na chance de sobrevivência?

A sobrevivência no Titanic foi definida por gênero e classe, mulheres e crianças tiveram prioridade absoluta, enquanto a 1ª classe garantiu maior acesso aos botes.
Além disso, o tamanho da família e a idade desempenharam papéis cruciais, indicando que indivíduos solitários e passageiros mais velhos enfrentaram barreiras para escapar com vida do naufrágio.